AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - "Rakefile"
    - "vendor/**/*"
    - "*.gemspec"
    - "Gemfile"
    - "docs/**/*"
    - "pkg/**/*"

RescueException:
  Enabled: false
